// <auto-generated />
using System;
using AuditBridge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditBridge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314000000_Sprint5Controls")]
    partial class Sprint5Controls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditBridge.Domain.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("AuditorId").HasColumnType("uuid").HasColumnName("auditor_id");
                    b.Property<string>("ClientEmail").HasColumnType("text").HasColumnName("client_email");
                    b.Property<string>("ClientOrgName").HasColumnType("text").HasColumnName("client_org_name");
                    b.Property<string>("ClientToken").HasColumnType("text").HasColumnName("client_token");
                    b.Property<DateTimeOffset?>("ClientTokenExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("client_token_expires_at");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<DateOnly?>("DueDate").HasColumnType("date").HasColumnName("due_date");
                    b.Property<string>("Metadata").IsRequired().HasColumnType("jsonb").HasColumnName("metadata");
                    b.Property<Guid>("OrgId").HasColumnType("uuid").HasColumnName("org_id");
                    b.Property<Guid>("ReferentialId").HasColumnType("uuid").HasColumnName("referential_id");
                    b.Property<string>("Scope").HasColumnType("text").HasColumnName("scope");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                    b.Property<string>("TemplateSnapshot").IsRequired().HasColumnType("jsonb").HasColumnName("template_snapshot");
                    b.Property<string>("Title").IsRequired().HasColumnType("text").HasColumnName("title");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("AuditorId");
                    b.HasIndex("OrgId");
                    b.HasIndex("ReferentialId");
                    b.ToTable("audits", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditCapa", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("ActionType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("action_type");
                    b.Property<bool>("AiGenerated").HasColumnType("boolean").HasColumnName("ai_generated");
                    b.Property<string>("AssignedToEmail").HasColumnType("text").HasColumnName("assigned_to_email");
                    b.Property<Guid>("AuditId").HasColumnType("uuid").HasColumnName("audit_id");
                    b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone").HasColumnName("completed_at");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<DateOnly?>("DueDate").HasColumnType("date").HasColumnName("due_date");
                    b.Property<string>("EvidencePath").HasColumnType("text").HasColumnName("evidence_path");
                    b.Property<Guid?>("FindingId").HasColumnType("uuid").HasColumnName("finding_id");
                    b.Property<string>("Metadata").IsRequired().HasColumnType("jsonb").HasColumnName("metadata");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("priority");
                    b.Property<Guid?>("QuestionId").HasColumnType("uuid").HasColumnName("question_id");
                    b.Property<Guid?>("ResponseId").HasColumnType("uuid").HasColumnName("response_id");
                    b.Property<string>("RootCause").HasColumnType("text").HasColumnName("root_cause");
                    b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("status");
                    b.Property<string>("Title").IsRequired().HasColumnType("text").HasColumnName("title");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.Property<Guid?>("VerifiedBy").HasColumnType("uuid").HasColumnName("verified_by");
                    b.HasKey("Id");
                    b.HasIndex("AuditId");
                    b.HasIndex("FindingId");
                    b.ToTable("audit_capas", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditEvidence", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("AuditId").HasColumnType("uuid").HasColumnName("audit_id");
                    b.Property<Guid?>("CapaId").HasColumnType("uuid").HasColumnName("capa_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<string>("FileName").IsRequired().HasColumnType("text").HasColumnName("file_name");
                    b.Property<long>("FileSizeBytes").HasColumnType("bigint").HasColumnName("file_size_bytes");
                    b.Property<Guid?>("FindingId").HasColumnType("uuid").HasColumnName("finding_id");
                    b.Property<string>("MimeType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("mime_type");
                    b.Property<Guid?>("ResponseId").HasColumnType("uuid").HasColumnName("response_id");
                    b.Property<string>("StoragePath").IsRequired().HasColumnType("text").HasColumnName("storage_path");
                    b.Property<Guid>("UploadedBy").HasColumnType("uuid").HasColumnName("uploaded_by");
                    b.HasKey("Id");
                    b.HasIndex("AuditId");
                    b.HasIndex("FindingId");
                    b.ToTable("audit_evidence", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditFinding", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("AuditId").HasColumnType("uuid").HasColumnName("audit_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<string>("FindingType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("finding_type");
                    b.Property<string>("ObservedEvidence").HasColumnType("text").HasColumnName("observed_evidence");
                    b.Property<Guid?>("QuestionId").HasColumnType("uuid").HasColumnName("question_id");
                    b.Property<string>("RegulatoryRef").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("regulatory_ref");
                    b.Property<Guid?>("ResponseId").HasColumnType("uuid").HasColumnName("response_id");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                    b.Property<string>("Title").IsRequired().HasColumnType("text").HasColumnName("title");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("AuditId");
                    b.ToTable("audit_findings", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditReport", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("AiNarrative").HasColumnType("text").HasColumnName("ai_narrative");
                    b.Property<Guid>("AuditId").HasColumnType("uuid").HasColumnName("audit_id");
                    b.Property<int?>("ConformCount").HasColumnType("integer").HasColumnName("conform_count");
                    b.Property<decimal?>("ConformityScore").HasColumnType("decimal(5,2)").HasColumnName("conformity_score");
                    b.Property<int>("CriticalNc").HasColumnType("integer").HasColumnName("critical_nc");
                    b.Property<string>("ExecutiveSummary").HasColumnType("text").HasColumnName("executive_summary");
                    b.Property<DateTimeOffset>("GeneratedAt").HasColumnType("timestamp with time zone").HasColumnName("generated_at");
                    b.Property<Guid?>("GeneratedBy").HasColumnType("uuid").HasColumnName("generated_by");
                    b.Property<int>("MajorNc").HasColumnType("integer").HasColumnName("major_nc");
                    b.Property<string>("Metadata").IsRequired().HasColumnType("jsonb").HasColumnName("metadata");
                    b.Property<int>("MinorNc").HasColumnType("integer").HasColumnName("minor_nc");
                    b.Property<int?>("NaCount").HasColumnType("integer").HasColumnName("na_count");
                    b.Property<int?>("NonConformCount").HasColumnType("integer").HasColumnName("non_conform_count");
                    b.Property<int?>("PartialCount").HasColumnType("integer").HasColumnName("partial_count");
                    b.Property<string>("PdfSha256").HasColumnType("text").HasColumnName("pdf_sha256");
                    b.Property<string>("PdfStoragePath").HasColumnType("text").HasColumnName("pdf_storage_path");
                    b.Property<string>("ReportData").IsRequired().HasColumnType("jsonb").HasColumnName("report_data");
                    b.Property<int?>("TotalQuestions").HasColumnType("integer").HasColumnName("total_questions");
                    b.Property<int>("Version").HasColumnType("integer").HasColumnName("version");
                    b.HasKey("Id");
                    b.HasIndex("AuditId").IsUnique();
                    b.ToTable("audit_reports", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditResponse", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("AiAnalysis").HasColumnType("jsonb").HasColumnName("ai_analysis");
                    b.Property<string>("AnswerNotes").HasColumnType("text").HasColumnName("answer_notes");
                    b.Property<string>("AnswerValue").HasColumnType("text").HasColumnName("answer_value");
                    b.Property<Guid?>("AnsweredBy").HasColumnType("uuid").HasColumnName("answered_by");
                    b.Property<bool>("AnsweredByClient").HasColumnType("boolean").HasColumnName("answered_by_client");
                    b.Property<Guid>("AuditId").HasColumnType("uuid").HasColumnName("audit_id");
                    b.Property<string>("AuditorComment").HasColumnType("text").HasColumnName("auditor_comment");
                    b.Property<string>("Conformity").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("conformity");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<bool>("IsFlagged").HasColumnType("boolean").HasColumnName("is_flagged");
                    b.Property<Guid>("QuestionId").HasColumnType("uuid").HasColumnName("question_id");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("AuditId");
                    b.HasIndex("QuestionId");
                    b.ToTable("audit_responses", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("action");
                    b.Property<Guid?>("ActorId").HasColumnType("uuid").HasColumnName("actor_id");
                    b.Property<string>("ActorType").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("actor_type");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<Guid>("EntityId").HasColumnType("uuid").HasColumnName("entity_id");
                    b.Property<string>("EntityType").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("entity_type");
                    b.Property<string>("IpAddress").HasColumnType("text").HasColumnName("ip_address");
                    b.Property<string>("NewValues").HasColumnType("jsonb").HasColumnName("new_values");
                    b.Property<string>("OldValues").HasColumnType("jsonb").HasColumnName("old_values");
                    b.Property<Guid>("TenantId").HasColumnType("uuid").HasColumnName("tenant_id");
                    b.Property<string>("UserAgent").HasColumnType("text").HasColumnName("user_agent");
                    b.HasKey("Id");
                    b.ToTable("audit_trail", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Control", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Category").HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("category");
                    b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("code");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<Guid>("OrgId").HasColumnType("uuid").HasColumnName("org_id");
                    b.Property<string>("Owner").HasColumnType("text").HasColumnName("owner");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                    b.Property<string>("Title").IsRequired().HasColumnType("text").HasColumnName("title");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("OrgId", "Code").IsUnique();
                    b.ToTable("controls", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.ControlMapping", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("ControlId").HasColumnType("uuid").HasColumnName("control_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Notes").HasColumnType("text").HasColumnName("notes");
                    b.Property<Guid>("ReferentialId").HasColumnType("uuid").HasColumnName("referential_id");
                    b.Property<Guid?>("SectionId").HasColumnType("uuid").HasColumnName("section_id");
                    b.Property<Guid?>("QuestionId").HasColumnType("uuid").HasColumnName("question_id");
                    b.HasKey("Id");
                    b.HasIndex("ControlId");
                    b.HasIndex("ReferentialId");
                    b.ToTable("control_mappings", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("CountryCode").IsRequired().HasMaxLength(2).HasColumnType("character varying(2)").HasColumnName("country_code");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true).HasColumnName("is_active");
                    b.Property<string>("Language").IsRequired().ValueGeneratedOnAdd().HasMaxLength(10).HasColumnType("character varying(10)").HasDefaultValue("fr").HasColumnName("language");
                    b.Property<string>("LogoUrl").HasColumnType("text").HasColumnName("logo_url");
                    b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("name");
                    b.Property<string>("Plan").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("character varying(20)").HasDefaultValue("starter").HasColumnName("plan");
                    b.Property<string>("StripeCustomerId").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("stripe_customer_id");
                    b.Property<string>("StripeSubscriptionId").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("stripe_subscription_id");
                    b.Property<string>("Type").IsRequired().HasColumnType("text").HasColumnName("type");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Referential", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid?>("CategoryId").HasColumnType("uuid").HasColumnName("category_id");
                    b.Property<string>("Code").IsRequired().HasColumnType("text").HasColumnName("code");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<bool>("IsPublic").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_public");
                    b.Property<bool>("IsSystem").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_system");
                    b.Property<string>("Metadata").IsRequired().HasColumnType("jsonb").HasColumnName("metadata");
                    b.Property<string>("Name").IsRequired().HasColumnType("text").HasColumnName("name");
                    b.Property<Guid?>("OrgId").HasColumnType("uuid").HasColumnName("org_id");
                    b.Property<Guid?>("OrganizationId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.Property<string>("Version").HasColumnType("text").HasColumnName("version");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("OrganizationId");
                    b.ToTable("referentials", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.ReferentialCategory", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("ColorHex").IsRequired().HasMaxLength(7).HasColumnType("character varying(7)").HasColumnName("color_hex");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Icon").HasColumnType("text").HasColumnName("icon");
                    b.Property<string>("Label").IsRequired().HasColumnType("text").HasColumnName("label");
                    b.Property<string>("Slug").IsRequired().HasColumnType("text").HasColumnName("slug");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("referential_categories", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.TemplateQuestion", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("AnswerOptions").HasColumnType("jsonb").HasColumnName("answer_options");
                    b.Property<string>("AnswerType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("answer_type");
                    b.Property<string>("Code").HasColumnType("text").HasColumnName("code");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Criticality").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("criticality");
                    b.Property<string[]>("ExpectedEvidence").HasColumnType("text[]").HasColumnName("expected_evidence");
                    b.Property<string>("Guidance").HasColumnType("text").HasColumnName("guidance");
                    b.Property<bool>("IsMandatory").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true).HasColumnName("is_mandatory");
                    b.Property<string>("Metadata").IsRequired().HasColumnType("jsonb").HasColumnName("metadata");
                    b.Property<int>("OrderIndex").HasColumnType("integer").HasColumnName("order_index");
                    b.Property<string>("Question").IsRequired().HasColumnType("text").HasColumnName("question");
                    b.Property<Guid>("ReferentialId").HasColumnType("uuid").HasColumnName("referential_id");
                    b.Property<Guid?>("SectionId").HasColumnType("uuid").HasColumnName("section_id");
                    b.Property<string[]>("Tags").HasColumnType("text[]").HasColumnName("tags");
                    b.HasKey("Id");
                    b.HasIndex("ReferentialId");
                    b.HasIndex("SectionId");
                    b.ToTable("template_questions", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.TemplateSection", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Code").HasColumnType("text").HasColumnName("code");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<int>("OrderIndex").HasColumnType("integer").HasColumnName("order_index");
                    b.Property<Guid?>("ParentId").HasColumnType("uuid").HasColumnName("parent_id");
                    b.Property<Guid>("ReferentialId").HasColumnType("uuid").HasColumnName("referential_id");
                    b.Property<string>("Title").IsRequired().HasColumnType("text").HasColumnName("title");
                    b.HasKey("Id");
                    b.HasIndex("ReferentialId");
                    b.ToTable("template_sections", (string)null);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("ClerkId").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("clerk_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("email");
                    b.Property<string>("FullName").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("full_name");
                    b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true).HasColumnName("is_active");
                    b.Property<DateTimeOffset?>("LastLoginAt").HasColumnType("timestamp with time zone").HasColumnName("last_login_at");
                    b.Property<Guid>("OrganizationId").HasColumnType("uuid").HasColumnName("organization_id");
                    b.Property<string>("Role").IsRequired().HasColumnType("text").HasColumnName("role");
                    b.HasKey("Id");
                    b.HasIndex("ClerkId").IsUnique();
                    b.HasIndex("OrganizationId");
                    b.ToTable("users", (string)null);
                });

            // ── Relationships ─────────────────────────────────────────────────

            modelBuilder.Entity("AuditBridge.Domain.Entities.Audit", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.User", null).WithMany().HasForeignKey("AuditorId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("AuditBridge.Domain.Entities.Organization", null).WithMany("Audits").HasForeignKey("OrgId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("AuditBridge.Domain.Entities.Referential", "Referential").WithMany().HasForeignKey("ReferentialId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Referential");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditCapa", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Audit", null).WithMany("Capas").HasForeignKey("AuditId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("AuditBridge.Domain.Entities.AuditFinding", null).WithMany("Capas").HasForeignKey("FindingId").OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditEvidence", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Audit", null).WithMany("Evidence").HasForeignKey("AuditId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("AuditBridge.Domain.Entities.AuditFinding", null).WithMany().HasForeignKey("FindingId").OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditFinding", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Audit", null).WithMany("Findings").HasForeignKey("AuditId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditReport", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Audit", null).WithOne().HasForeignKey("AuditBridge.Domain.Entities.AuditReport", "AuditId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditResponse", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Audit", null).WithMany("Responses").HasForeignKey("AuditId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("AuditBridge.Domain.Entities.TemplateQuestion", null).WithMany().HasForeignKey("QuestionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Control", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Organization", null).WithMany().HasForeignKey("OrgId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.ControlMapping", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Control", "Control").WithMany("Mappings").HasForeignKey("ControlId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("AuditBridge.Domain.Entities.Referential", null).WithMany().HasForeignKey("ReferentialId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Control");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Referential", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.ReferentialCategory", "Category").WithMany().HasForeignKey("CategoryId");
                    b.HasOne("AuditBridge.Domain.Entities.Organization", null).WithMany("Referentials").HasForeignKey("OrganizationId");
                    b.Navigation("Category");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.TemplateQuestion", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Referential", null).WithMany("Questions").HasForeignKey("ReferentialId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("AuditBridge.Domain.Entities.TemplateSection", null).WithMany("Questions").HasForeignKey("SectionId");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.TemplateSection", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Referential", null).WithMany("Sections").HasForeignKey("ReferentialId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.User", b =>
                {
                    b.HasOne("AuditBridge.Domain.Entities.Organization", "Organization").WithMany("Users").HasForeignKey("OrganizationId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Audit", b =>
                {
                    b.Navigation("Capas");
                    b.Navigation("Evidence");
                    b.Navigation("Findings");
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.AuditFinding", b =>
                {
                    b.Navigation("Capas");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Control", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Audits");
                    b.Navigation("Referentials");
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.Referential", b =>
                {
                    b.Navigation("Questions");
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AuditBridge.Domain.Entities.TemplateSection", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
